# Generated by Django 3.2.8 on 2021-12-25 08:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
